name: Build and Attach Resume PDF to Release

on:
  push:
    branches:
      - main

# Add permissions block
permissions:
  contents: write  # Required for creating releases
  packages: write  # Required for uploading release assets

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install dependencies
        run: npm ci

      - name: Get version
        id: get_version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          # Extract version number
          version=$(echo $latest_tag | sed 's/v//')
          # Split into major, minor, patch
          IFS='.' read -r major minor patch <<< "$version"
          # Increment patch version
          new_patch=$((patch + 1))
          # Create new version
          new_version="v$major.$minor.$new_patch"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Build resume PDF
        run: npm run build-and-run
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
          RESUME_VERSION: ${{ steps.get_version.outputs.new_version }}

      - name: Verify PDF exists
        run: |
          PDF_PATH="output/rory-mcdaniel-resume-${{ steps.get_version.outputs.new_version }}.pdf"
          if [ ! -f "$PDF_PATH" ]; then
            echo "PDF file not found at $PDF_PATH"
            ls -la output/
            exit 1
          fi
          echo "PDF file found at $PDF_PATH"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.new_version }}
          name: Resume ${{ steps.get_version.outputs.new_version }}
          files: |
            output/rory-mcdaniel-resume-${{ steps.get_version.outputs.new_version }}.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}